function Circuit_HPF

Fig=figure('Name','HPF',...
'NumberTitle','off');
w= imread('High_pass_filter.bmp'); 
imshow(w, 'InitialMagnification', 150); 
title('HIGH PASS FILTER');
xlabel('fo = 1 / 2*pi*R*C');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.78 0.03 0.2 0.08],...
'String','CLOSE',...
'Callback','close;');
end