function Circuit_LPF

Fig=figure('Name','LPF',...
'NumberTitle','off');
w= imread('Stickers_Unicorns_Read.png'); 
imshow(w, 'InitialMagnification', 150); 
title('LOW PASS FILTER');
xlabel('fo = 1 / 2*pi*R*C');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.78 0.03 0.2 0.08],...
'String','CLOSE',...
'Callback','close;');
end