function LowPassFilter
i=imread('Low_pass_filter.bmp');
%displays the image
image(i)
title('LOW PASS FILTER');%pushbutton for Close
uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.78 0.03 0.2 0.07],...
'String','CLOSE',...
'Callback','close');
end