Fig=figure('Name','Front',...
'Position',[300 300 300 200],...
'NumberTitle','off');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.025 0.5 0.3 0.1],...
'BackgroundColor',[1 0 0],...
'String','Documentatie',...
'Callback','Documentatie');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.35 0.5 0.3 0.1],...
'String','Frequency',...
'BackgroundColor',[0 1 0],...
'Callback','tfd_gui');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[ 0.78 0.03 0.2 0.08],...
'String','Unicorn',...
'BackgroundColor',[0 1 1],...
'Callback','Unicorn');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.67 0.5 0.3 0.1],...
'String','BMI',...
'BackgroundColor',[1 1 0],...
'Callback','Bodymassindex');

ha = axes('units','normalized', ...
            'position',[0 0 1 1]);
uistack(ha,'bottom');
I=imread('BreakingDownBarriersFitness.jpg');
hi = imagesc(I);
colormap gray
set(ha,'handlevisibility','off', ...
            'visible','off')