function sincos_plots
clear all;	
Fig=figure('Name','Plotari',...
'NumberTitle','off');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.025 0.937 0.3 0.05],...
'String','SINE',...
'Callback','sine');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.7 0.937 0.3 0.05],...
'String','COSINE',...
'Callback','cosine');

uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.8 0.001 0.2 0.04],...
'String','CLOSE',...
'Callback','close;');
end