function Unicorn 

Fig=figure('Name','LPF',...
'NumberTitle','off');
w= imread('Stickers_Unicorns_Read.png'); 
imshow(w, 'InitialMagnification', 150); 
title('LUCKY UNICORN PICTURE');


uicontrol('Style','pushbutton',...
'Units','normalized',...
'Position',[0.78 0.03 0.2 0.08],...
'String','CLOSE',...
'Callback','close;');
end