%1. Main_script.m

clear;
close all;
clc;


VDC = 10;
R=3;
C=2;
T=6;
D=0.5;
N=7;

Fig=figure('Name','Time domain behavior of an RC circuit ');

% text button for V_DC
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.91 0.95 0.1 0.04], ...
    'String','VDC');

% edit button for V_DC
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.92 0.1 0.04],...
    'String',num2str(VDC),... 
    'Callback',['VDC=str2num(get(gco,''string''));interface_RC(VDC,R,C,T,D,N);']);
    
% text button for R
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.91 0.85 0.1 0.04], ...
    'String','R');

% edit button for R
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.82 0.1 0.04],...
    'String',num2str(R),...
    'Callback','R=str2num(get(gco,''string''));interface_RC(VDC,R,C,T,D,N);');

% text button for C
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.91 0.75 0.1 0.04], ...
    'String','C');

% edit button for C
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.72 0.1 0.04],...
    'String',num2str(C),...
    'Callback','C=str2num(get(gco,''string''));interface_RC(VDC,R,C,T,D,N);');

% text button for T
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.91 0.65 0.1 0.04], ...
    'String','T');

% edit button for T
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.62 0.1 0.04],...
    'String',num2str(T),...
    'Callback','T=str2num(get(gco,''string''));interface_RC(VDC,R,C,T,D,N);');

% text button for D
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.91 0.55 0.1 0.04], ...
    'String','D');

% edit button for D
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.52 0.1 0.04],...
    'String',num2str(D),...
    'Callback','D=str2num(get(gco,''string''));interface_RC(VDC,R,C,T,D,N);');

% text button for N
uicontrol('Style','text', ...
    'Units','normalized', ...
    'Position',[0.91 0.45 0.1 0.04], ...
    'String','N');

% edit button for N
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.42 0.1 0.04],...
    'String',num2str(N),...
    'Callback','N=str2num(get(gco,''string''));interface_RC(VDC,R,C,T,D,N);');

% Close pushbutton for closing the graph window
uicontrol('Style','pushbutton', ...
    'Units','normalized', ...
    'Position',[0.91 0.15 0.1 0.04], ...
    'String','CLOSE', ...
    'Callback','close; ');

interface_RC(VDC,R,C,T,D,N);